version: '3'
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pendrive
      MYSQL_PASSWORD: pendrive
      MYSQL_DATABASE: calc

  calcapi:
    build: .
    restart: unless-stopped
    command: gunicorn --config gunicorn_config.py app:app
    env_file:
      - ./.env
    links:
      - mysql:mysql
    depends_on:
      - mysql
    ports:
      - 5000:5000

volumes:
  db-data:
