
export interface Country {
    name: string;
    iso2: string;
    }
export interface User {
    id: number;
    email: string;
    password: string;
    first_name: string;
    last_name: string;
    user_role: string;
    user_country: string;
    user_language: string;
    language: string;
    country: string;
    fx: string;
    street: string;
    nr: string;
    zipcode: string;
    city: string;
}
export const UserEmpty = {
    id: 0,
    email: '',
    password: '',
    first_name: '',
    last_name: '',
    user_role: '',
    user_country: '',
    user_language: '',
    language: '',
    country: '',
    fx: '',
    street: '',
    nr: '',
    zipcode: '',
    city: ''
}
export interface IndividualStatus {
    basis: boolean;
    individual: boolean;
    special: boolean;
    household: boolean;
    livingspace: boolean;
    projectcost: boolean;
    documents: boolean;    
}

export interface UserAddress {
    street: string;
    nr: string;
    zipcode: string;
    city: string;
    country: number;
}
export interface Basis {
    user_id: number,
    country_id: number,
    employment_type: string,
    interest_variant: string,
    loan_amount: number,
    loan_term: number,
    purchasing: number,
    purpose: string,
    type_property: string,
    preferred_date: Date
}
export interface AdditionalProject {
    fx: string,
    type_property: string,
    land_registry: number,
    land_registry_val: number,
    land_bank: number,
    land_bank_val: number
}

export const ContentsCommon =[
    {
        name: 'general', 
        title: 'General', 
        children: [
            {name: 'back', title: 'Back'},
            {name: 'next', title: 'Next'},
            {name: 'save', title: 'Save'},
            {name: 'delete', title: 'Delete'},
            {name: 'settings', title: 'Settitngs'},
            {name: 'find_your_best_rate', title: 'Find your best rate'},
            {name: 'awarded_agency', title: 'Awarded Agency'},
            {name: 'free_revisions', title: 'Free Revisions'},
            {name: 'verified_company', title: 'Verified Company'},
        ]
    },
    {
        name: 'menu', 
        title: 'Menu', 
        children: [
            {name: 'home', title: 'Home'},
            {name: 'free_trial', title: 'Free Trial'},
            {name: 'basis', title: 'Loan data'},
            {name: 'individual', title: 'Personal data'},
            {name: 'overview', title: 'Overview'},
            {name: 'dashboard', title: 'Dashboard'},
            {name: 'calculation', title: 'Calculation'},
            {name: 'special', title: 'Project data'},
            {name: 'household', title: 'Household bill'},
            {name: 'livingspace', title: 'Living space'},
            {name: 'projectcost', title: 'Project costs'},
            {name: 'documents', title: 'Documents'},
            {name: 'contents', title: 'Contents'},
            {name: 'users', title: 'Users'},
            {name: 'languages', title: 'Languages'},
            {name: 'countries', title: 'Countries'}
        ]
    },
    {
        name: 'login', 
        title: 'Login/Register', 
        children: [
            {name: 'login', title: 'Sign in'},
            {name: 'welcome_back', title: 'Welcome back'},
            {name: 'sign_with_credentials', title: 'Sign in with your credentials below'},
            {name: 'email', title: 'E-Mail'},
            {name: 'firstname', title: 'First Name'},
            {name: 'lastname', title: 'Last Name'},
            {name: 'password', title: 'Password'},
            {name: 'password_confirm', title: 'Confirm password'},
            {name: 'password_match', title: 'Password must match'},
            {name: 'registration', title: 'Register for an account'},
            {name: 'simply_fill', title: 'Simply fill out the form below'},
            {name: 'register', title: 'Sign up'},
            {name: 'create_account', title: 'Create account'},
            {name: 'already_account', title: 'Already have an account?'},
            {name: 'sign_here', title: "Sign in here"},
            {name: 'donot_account', title: "Don't have an account?"},
            {name: 'click_here_create', title: "Click here to create one"},
            {name: 'whoAreYou', title: 'Q1: Who are you?'},
            {name: 'individual', title: 'DD: Individual'},
            {name: 'content', title: 'DD: Content provider'},
            {name: 'both', title: 'DD: Both'},
            {name: 'whereAreYouFrom', title: 'Q2: Where are you from?'},
            {name: 'preferredLanguage', title: 'Q3: Preferred Language?'},
            {name: 'language', title: 'Language'},
            {name: 'errorRequired', title: 'This field must be required'},
            {name: 'toggle_visibility', title: 'Toggle visibility'},
            {name: 'click_eye', title: 'Click the eye to toggle visibility'},
            {name: 'repeat_password', title: 'Please repeat your password from above'},
            {name: 'remember_me', title: 'Remember Me'},
            {name: 'forgot_password', title: 'Forgot Password'}
        ]
    }  
];
export const ContentsProvider = 
[ 
    { 
    "id":1,
    "name":"interest_variant",
    "val":"Interest rate variant",
    "level":1,
    "parent_id":0,
    "category":"contents",
    "variety":"general",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":2,
    "name":"interest_accepted",
    "val":"Interest accepted",
    "level":2,
    "parent_id":1,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":"",
    "created":null
    },
    { 
    "id":3,
    "name":"interest_fixed",
    "val":"Fixed rate",
    "level":2,
    "parent_id":1,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":4,
    "name":"surcharge_5",
    "val":"5",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":5,
    "name":"surcharge_10",
    "val":"10",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":6,
    "name":"surcharge_15",
    "val":"15",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":7,
    "name":"surcharge_20",
    "val":"20",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":8,
    "name":"surcharge_25",
    "val":"25",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":9,
    "name":"surcharge_30",
    "val":"30",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":10,
    "name":"surcharge_35",
    "val":"35",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":11,
    "name":"surcharge_40",
    "val":"40",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":12,
    "name":"surcharge_45",
    "val":"45",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":13,
    "name":"surcharge_50",
    "val":"50",
    "level":2,
    "parent_id":1,
    "category":"content_surcharges",
    "variety":"number",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":14,
    "name":"interest_reference",
    "val":"Choose rate",
    "level":2,
    "parent_id":1,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":15,
    "name":"internal_costs",
    "val":"Internal costs",
    "level":1,
    "parent_id":0,
    "category":"contents",
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":16,
    "name":"funding_case",
    "val":"Funding per case ",
    "level":1,
    "parent_id":0,
    "category":"contents",
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":17,
    "name":"funding_case_min",
    "val":"Minimum",
    "level":2,
    "parent_id":16,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":18,
    "name":"funding_case_max",
    "val":"Maximum",
    "level":2,
    "parent_id":16,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":19,
    "name":"purpose",
    "val":"Purpose",
    "level":1,
    "parent_id":0,
    "category":"content_reductions",
    "variety":"basis",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":20,
    "name":"purpose_buy",
    "val":"Buy property",
    "level":2,
    "parent_id":19,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":21,
    "name":"purpose_build",
    "val":"Build property",
    "level":2,
    "parent_id":19,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":22,
    "name":"purpose_modification",
    "val":"Modification",
    "level":2,
    "parent_id":19,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":23,
    "name":"purpose_rescheduling",
    "val":"Rescheduling",
    "level":2,
    "parent_id":19,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":24,
    "name":"purpose_else",
    "val":"Else",
    "level":2,
    "parent_id":19,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":25,
    "name":"type_property",
    "val":"Type of property",
    "level":1,
    "parent_id":0,
    "category":"content_reductions",
    "variety":"basis",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":26,
    "name":"type_condo",
    "val":"Condo",
    "level":2,
    "parent_id":25,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":27,
    "name":"type_single",
    "val":"Single-family home",
    "level":2,
    "parent_id":25,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":28,
    "name":"type_duplex",
    "val":"Duplex",
    "level":2,
    "parent_id":25,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":29,
    "name":"type_semidetached",
    "val":"Semidetaced house",
    "level":2,
    "parent_id":25,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":30,
    "name":"type_row",
    "val":"Row home",
    "level":2,
    "parent_id":25,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":31,
    "name":"type_multi",
    "val":"Multi-family home",
    "level":2,
    "parent_id":25,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":32,
    "name":"type_developable",
    "val":"Developable plot",
    "level":2,
    "parent_id":25,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":33,
    "name":"type_cooperative",
    "val":"Co-operative flat",
    "level":2,
    "parent_id":25,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":34,
    "name":"type_else",
    "val":"Else",
    "level":2,
    "parent_id":25,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":35,
    "name":"purchasing",
    "val":"Purchasing price/Property value",
    "level":1,
    "parent_id":0,
    "category":"content_ranges",
    "variety":"basis",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":36,
    "name":"purchasing_min",
    "val":"Minimum",
    "level":2,
    "parent_id":35,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":37,
    "name":"purchasing_max",
    "val":"Maximum",
    "level":2,
    "parent_id":35,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":38,
    "name":"purchasing_reduction_starting",
    "val":"Reduction starting",
    "level":2,
    "parent_id":35,
    "category":"content_reductions",
    "variety":"content_reductions",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":39,
    "name":"purchasing_reduction",
    "val":"Reduction",
    "level":2,
    "parent_id":35,
    "category":"content_reductions",
    "variety":"content_reductions",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":40,
    "name":"loan_amount",
    "val":"Loan amount required",
    "level":1,
    "parent_id":0,
    "category":"content_ranges",
    "variety":"basis",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":41,
    "name":"loan_amount_min",
    "val":"Minimum",
    "level":2,
    "parent_id":40,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":42,
    "name":"loan_amount_max",
    "val":"Maximum",
    "level":2,
    "parent_id":40,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":43,
    "name":"loan_term",
    "val":"Loan term(years)",
    "level":1,
    "parent_id":0,
    "category":"content_ranges",
    "variety":"basis",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":44,
    "name":"loan_term_min",
    "val":"Minimum",
    "level":2,
    "parent_id":43,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":45,
    "name":"loan_term_max",
    "val":"Maximum",
    "level":2,
    "parent_id":43,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":46,
    "name":"employment_type",
    "val":"Employment type",
    "level":1,
    "parent_id":0,
    "category":"content_reductions",
    "variety":"basis",
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":47,
    "name":"employment_employee",
    "val":"Employee",
    "level":2,
    "parent_id":46,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":48,
    "name":"employment_worker",
    "val":"Worker",
    "level":2,
    "parent_id":46,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":49,
    "name":"employment_official",
    "val":"Official",
    "level":2,
    "parent_id":46,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":50,
    "name":"employment_self",
    "val":"Self-employed",
    "level":2,
    "parent_id":46,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":51,
    "name":"employment_student",
    "val":"Student",
    "level":2,
    "parent_id":46,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":52,
    "name":"employment_unemployed",
    "val":"Unemployed",
    "level":2,
    "parent_id":46,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":53,
    "name":"employment_renter",
    "val":"Renter",
    "level":2,
    "parent_id":46,
    "category":"content_reductions",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":54,
    "name":"martial_status",
    "val":"Martial status",
    "level":1,
    "parent_id":0,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":55,
    "name":"martial_single",
    "val":"Single",
    "level":2,
    "parent_id":54,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":56,
    "name":"martial_relationship",
    "val":"Relationship",
    "level":2,
    "parent_id":54,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":57,
    "name":"martial_married",
    "val":"Martial Married",
    "level":2,
    "parent_id":54,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":58,
    "name":"age",
    "val":"Age",
    "level":1,
    "parent_id":0,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":59,
    "name":"age_min",
    "val":"Minimum",
    "level":2,
    "parent_id":58,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":60,
    "name":"age_max",
    "val":"Maximum",
    "level":2,
    "parent_id":58,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":61,
    "name":"age_18",
    "val":"18-25",
    "level":2,
    "parent_id":58,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":62,
    "name":"age_26",
    "val":"26-35",
    "level":2,
    "parent_id":58,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":63,
    "name":"age_36",
    "val":"36-45",
    "level":2,
    "parent_id":58,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":64,
    "name":"age_46",
    "val":"46-55",
    "level":2,
    "parent_id":58,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":65,
    "name":"age_56",
    "val":"56-65",
    "level":2,
    "parent_id":58,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":66,
    "name":"age_66",
    "val":"66-75",
    "level":2,
    "parent_id":58,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":67,
    "name":"age_76",
    "val":"From 76",
    "level":2,
    "parent_id":58,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":68,
    "name":"net_income",
    "val":"Net income",
    "level":1,
    "parent_id":0,
    "category":"contents",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":69,
    "name":"net_min",
    "val":"Minimum",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":"net_usual",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":70,
    "name":"net_not_ratio",
    "val":"Not accepted ratio",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":"net_usual",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":71,
    "name":"net_ratio_1",
    "val":"Ratio",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":"net_ratio",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":72,
    "name":"net_reduction_surcharge_1",
    "val":"Reduction/Surcharge",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":"net_reduction_surcharge",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":73,
    "name":"net_reduction",
    "val":"Reduction",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":74,
    "name":"highest_degree",
    "val":"Highest degree",
    "level":1,
    "parent_id":0,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":75,
    "name":"highest_compulsory",
    "val":"Compulsory education",
    "level":2,
    "parent_id":74,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":76,
    "name":"highest_diploma",
    "val":"High school diploma",
    "level":2,
    "parent_id":74,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":77,
    "name":"highest_master",
    "val":"Bachelor/Master Degree o.e.",
    "level":2,
    "parent_id":74,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":78,
    "name":"highest_doctorate",
    "val":"Doctorate",
    "level":2,
    "parent_id":74,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":79,
    "name":"field_work",
    "val":"Field of work",
    "level":1,
    "parent_id":0,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":80,
    "name":"field_banking",
    "val":"Banking/Insurance",
    "level":2,
    "parent_id":79,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":81,
    "name":"field_commerce",
    "val":"Commerce",
    "level":2,
    "parent_id":79,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":82,
    "name":"field_agricultural",
    "val":"Agricultural",
    "level":2,
    "parent_id":79,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":83,
    "name":"field_healthcare",
    "val":"Healthcare/Pharma",
    "level":2,
    "parent_id":79,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":84,
    "name":"field_construction",
    "val":"Construction",
    "level":2,
    "parent_id":79,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":85,
    "name":"field_it",
    "val":"IT/Internet",
    "level":2,
    "parent_id":79,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":86,
    "name":"field_services",
    "val":"Services",
    "level":2,
    "parent_id":79,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":87,
    "name":"field_else",
    "val":"Else",
    "level":2,
    "parent_id":79,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":88,
    "name":"job_position",
    "val":"Job position",
    "level":1,
    "parent_id":0,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":89,
    "name":"job_employed",
    "val":"Employed",
    "level":2,
    "parent_id":88,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":90,
    "name":"job_leading",
    "val":"Leading position",
    "level":2,
    "parent_id":88,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":91,
    "name":"job_managind",
    "val":"Managind Director",
    "level":2,
    "parent_id":88,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":92,
    "name":"job_clevel",
    "val":"C-Level",
    "level":2,
    "parent_id":88,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":93,
    "name":"kids",
    "val":"Number of kids",
    "level":1,
    "parent_id":0,
    "category":"content_reductions",
    "variety":"individual",
    "lang_need":null,
    "page":"individual",
    "created":null
    },
    { 
    "id":94,
    "name":"kids_min",
    "val":"Minimum",
    "level":2,
    "parent_id":93,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":95,
    "name":"kids_max",
    "val":"Maximum",
    "level":2,
    "parent_id":93,
    "category":"content_ranges",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":96,
    "name":"kids_1",
    "val":"1",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":97,
    "name":"kids_2",
    "val":"2",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":98,
    "name":"kids_3",
    "val":"3",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":99,
    "name":"kids_4",
    "val":"4",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":100,
    "name":"kids_5",
    "val":"5",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":101,
    "name":"kids_6",
    "val":"6",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":102,
    "name":"kids_7",
    "val":"7",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":103,
    "name":"kids_8",
    "val":"8",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":104,
    "name":"kids_9",
    "val":"9",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":105,
    "name":"kids_10",
    "val":"10",
    "level":2,
    "parent_id":93,
    "category":"content_reductions",
    "variety":"number",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":106,
    "name":"address",
    "val":"Address",
    "level":1,
    "parent_id":0,
    "category":"contents",
    "variety":"special",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":107,
    "name":"address_scope",
    "val":"Countries",
    "level":2,
    "parent_id":106,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":108,
    "name":"country_id",
    "val":"Choose countries",
    "level":2,
    "parent_id":106,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":109,
    "name":"self_funds",
    "val":"Self funds",
    "level":1,
    "parent_id":0,
    "category":"content_guarantors",
    "variety":"special",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":110,
    "name":"self_required",
    "val":"Self funds required",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"required",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":111,
    "name":"self_min",
    "val":"Minimum",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"mini",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":112,
    "name":"self_until_1",
    "val":"until_1",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":113,
    "name":"self_reduction_1",
    "val":"reduction_1",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":114,
    "name":"guarantor",
    "val":"Guarantor",
    "level":1,
    "parent_id":0,
    "category":"content_guarantors",
    "variety":"special",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":115,
    "name":"guarantor_required",
    "val":"Guarantor accepted",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"required",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":116,
    "name":"guarantor_min",
    "val":"Minimum",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"mini",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":117,
    "name":"guarantor_until_1",
    "val":"until_1",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":118,
    "name":"guarantor_reduction_1",
    "val":"reduction_1",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":119,
    "name":"combined",
    "val":"Combined self funds/guarantor",
    "level":1,
    "parent_id":0,
    "category":"content_guarantors",
    "variety":"special",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":120,
    "name":"combined_required",
    "val":"Combined accepted",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"required",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":121,
    "name":"combined_min",
    "val":"Minimum",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"mini",
    "lang_need": null,
    "page":null,
    "created":null
    },
    { 
    "id":122,
    "name":"combined_until_1",
    "val":"until_1",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":123,
    "name":"combined_reduction_1",
    "val":"reduction_1",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":124,
    "name":"internal_val",
    "val":"Internal costs value",
    "level":2,
    "parent_id":15,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":125,
    "name":"interest_accepted_variable",
    "val":"Variable",
    "level":3,
    "parent_id":2,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":"basis",
    "created":null
    },
    { 
    "id":126,
    "name":"interest_accepted_fixed",
    "val":"Fixed",
    "level":3,
    "parent_id":2,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":"",
    "created":null
    },
    { 
    "id":127,
    "name":"interest_accepted_both",
    "val":"Both",
    "level":3,
    "parent_id":2,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":"",
    "created":null
    },
    { 
    "id":128,
    "name":"interest_reference_1",
    "val":"Reference 1",
    "level":3,
    "parent_id":14,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":129,
    "name":"interest_reference_2",
    "val":"Reference 2",
    "level":3,
    "parent_id":14,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":130,
    "name":"all_countries",
    "val":"All Countries",
    "level":3,
    "parent_id":107,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":131,
    "name":"individual_countries",
    "val":"Individual countries",
    "level":3,
    "parent_id":107,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":132,
    "name":"general",
    "val":"General",
    "level":1,
    "parent_id":0,
    "category":null,
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":135,
    "name":"not_accepted",
    "val":"Not Accepted",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":136,
    "name":"no_reduction",
    "val":"No Reduction",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":137,
    "name":"content_provider",
    "val":"Content Provider",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":138,
    "name":"no",
    "val":"No",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":139,
    "name":"yes",
    "val":"Yes",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":140,
    "name":"interest_years",
    "val":"Years",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":141,
    "name":"interest_status",
    "val":"Status",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":142,
    "name":"interest_surcharge",
    "val":"Surcharge",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":143,
    "name":"expand_all",
    "val":"Expand All",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":144,
    "name":"collapse_all",
    "val":"Collapse All",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":145,
    "name":"save",
    "val":"Save",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":146,
    "name":"guarantor_reduction_2",
    "val":"reduction_2",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":147,
    "name":"guarantor_reduction_3",
    "val":"reduction_3",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":148,
    "name":"guarantor_reduction_4",
    "val":"reduction_4",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":149,
    "name":"guarantor_reduction_5",
    "val":"reduction_5",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":150,
    "name":"guarantor_until_2",
    "val":"until_2",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":151,
    "name":"guarantor_until_3",
    "val":"until_3",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":152,
    "name":"guarantor_until_4",
    "val":"until_4",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":153,
    "name":"guarantor_until_5",
    "val":"until_5",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":154,
    "name":"self_until_2",
    "val":"until_2",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":155,
    "name":"self_until_3",
    "val":"until_3",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":156,
    "name":"self_until_4",
    "val":"until_4",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":157,
    "name":"self_until_5",
    "val":"until_5",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":202,
    "name":"self_reduction_2",
    "val":"reduction_2",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":203,
    "name":"self_reduction_3",
    "val":"reduction_3",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":204,
    "name":"self_reduction_4",
    "val":"reduction_4",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":205,
    "name":"self_reduction_5",
    "val":"reduction_5",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":206,
    "name":"combined_until_2",
    "val":"until_2",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":207,
    "name":"combined_until_3",
    "val":"until_3",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":208,
    "name":"combined_until_4",
    "val":"until_4",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":209,
    "name":"combined_until_5",
    "val":"until_5",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"until",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":210,
    "name":"combined_reduction_2",
    "val":"reduction_2",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":211,
    "name":"combined_reduction_3",
    "val":"reduction_3",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":212,
    "name":"combined_reduction_4",
    "val":"reduction_4",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":213,
    "name":"combined_reduction_5",
    "val":"reduction_5",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"reduction",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":217,
    "name":"self_reduction_to",
    "val":"reduction_to",
    "level":2,
    "parent_id":109,
    "category":"content_guarantors",
    "variety":"reduction_to",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":218,
    "name":"guarantor_reduction_to",
    "val":"reduction_to",
    "level":2,
    "parent_id":114,
    "category":"content_guarantors",
    "variety":"reduction_to",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":219,
    "name":"combined_reduction_to",
    "val":"reduction_to",
    "level":2,
    "parent_id":119,
    "category":"content_guarantors",
    "variety":"reduction_to",
    "lang_need":"0",
    "page":null,
    "created":null
    },
    { 
    "id":220,
    "name":"net_ratio_3",
    "val":"Ratio",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":"net_ratio",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":221,
    "name":"net_ratio_2",
    "val":"Ratio",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":"net_ratio",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":222,
    "name":"net_reduction_surcharge_3",
    "val":"Reduction/Surcharge",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":"net_reduction_surcharge",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":223,
    "name":"net_reduction_surcharge_2",
    "val":"Reduction/Surcharge",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":"net_reduction_surcharge",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":224,
    "name":"net_to",
    "val":"net_to",
    "level":2,
    "parent_id":68,
    "category":"contents",
    "variety":"net_income_to",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":225,
    "name":"kids_to",
    "val":"kids_to",
    "level":2,
    "parent_id":93,
    "category":"contents",
    "variety":"kids_to",
    "lang_need":0,
    "page":null,
    "created":null
    },
    { 
    "id":226,
    "name":"general",
    "val":"General",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":227,
    "name":"special",
    "val":"Special",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":228,
    "name":"individual",
    "val":"Individual",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":229,
    "name":"basic",
    "val":"Basic",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":232,
    "name":"validate_error",
    "val":"Insert data correctly!",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":233,
    "name":"updated_msg",
    "val":"Updated Successfully!",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":234,
    "name":"created_msg",
    "val":"Created Successfully!",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":235,
    "name":"interest_variant_tip",
    "val":"Interest rate variant",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":236,
    "name":"internal_costs_tip",
    "val":"Internal costs",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":237,
    "name":"funding_case_tip",
    "val":"Funding per case",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":238,
    "name":"purpose_tip",
    "val":"Purpose",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":239,
    "name":"type_property_tip",
    "val":"Type of property",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":240,
    "name":"purchasing_tip",
    "val":"Purchasing price/Property value",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":241,
    "name":"loan_amount_tip",
    "val":"Loan amount required",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":242,
    "name":"loan_term_tip",
    "val":"Loan term(years)",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":243,
    "name":"employment_type_tip",
    "val":"Employment type",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":244,
    "name":"martial_status_tip",
    "val":"Martial status",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":245,
    "name":"age_tip",
    "val":"Age",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":246,
    "name":"net_income_tip",
    "val":"Net income",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":247,
    "name":"highest_degree_tip",
    "val":"Highest degree",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":248,
    "name":"field_work_tip",
    "val":"Field of work",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":249,
    "name":"job_position_tip",
    "val":"Job position",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":250,
    "name":"kids_tip",
    "val":"Number of kids",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":251,
    "name":"address_tip",
    "val":"Address",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":252,
    "name":"self_funds_tip",
    "val":"Self funds",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":253,
    "name":"guarantor_tip",
    "val":"Guarantor",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":254,
    "name":"combined_tip",
    "val":"Combined self funds/guarantor",
    "level":2,
    "parent_id":262,
    "category":null,
    "variety":"tip",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":255,
    "name":"reduction",
    "val":"Reduction",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":256,
    "name":"until",
    "val":"Until",
    "level":2,
    "parent_id":132,
    "category":null,
    "variety":"general",
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":257,
    "name":"address_all",
    "val":"All Countries",
    "level":100,
    "parent_id":107,
    "category":"contents",
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":258,
    "name":"address_choose",
    "val":"Choose Countries",
    "level":100,
    "parent_id":107,
    "category":null,
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
    },
    { 
    "id":262,
    "name":"tip",
    "val":"Tips",
    "level":1,
    "parent_id":0,
    "category":null,
    "variety":null,
    "lang_need":null,
    "page":null,
    "created":null
}];
export const ContentsIndividual = [
    {
        name: 'general',
        title: 'General',
        children: [
            {name: 'calculation', title: 'Calculation',type: ''},
            {name: 'results', title: 'Results',type: ''}
        ]
    },
    {
        name: 'overview',
        title: 'Overview',
        // children: [
        //     {name: 'basis', title: 'Basis data'},
        //     {name: 'individual', title: 'Individual data'},
        //     {name: 'special', title: 'Special data'},
        //     {name: 'household', title: 'Household bill'},
        //     {name: 'livingspace', title: 'Living space'},
        //     {name: 'projectcost', title: 'Project cost'},
        //     {name: 'documents', title: 'Documents'},
        // ]
        children: [
            {name: 'basis', title: 'Loan data',type: ''},
            {name: 'individual', title: 'personal data',type: ''},
            {name: 'special', title: 'Project data',type: ''},
            {name: 'household', title: 'Household bill',type: ''},
            {name: 'livingspace', title: 'Living space',type: ''},
            {name: 'projectcost', title: 'Project costs',type: ''},
            {name: 'documents', title: 'Documents',type: ''},
        ]
    },
    {
        name: 'basis',
        title: 'Loan data',
        children: [
            {name: 'guide', title: 'Input below data to get basic payment rate', type: ''},
            {name: 'preferred_date', title: 'Preferred payout date', type: ''},
            {name: 'analysis', title: 'Analyse', type: ''},
            {name: 'anaysis_potential', title: 'Analysis Potential', type: ''},
            {name: 'from', title: 'From', type: ''},
            {name: 'to', title: 'To', type: ''},
            {name: 'payment_rate', title: 'Payment rate', type: ''},
            {name: 'borrowing_rate', title: 'Borrowing rate', type: ''},
            {name: 'effective_rate', title: 'Effective rate', type: ''},
            {name: 'total_payment', title: 'Total payment', type: ''},
            {name: 'result_based', title: 'Based on your information, we currently assume a nominal interest rate of', type: ''},
            {name: 'result_to', title: 'to', type: ''},
            {name: 'result_addition', title: 'In addition, we have factored in the following for the effective interest rate:', type: ''},
            {name: 'result_state', title: 'State taxes: registration of', type: ''},
            {name: 'result_bank', title: 'bank lien', type: ''},
            {name: 'result_info', title: 'Information requested from the bank: credit report', type: ''},
            {name: 'result_land', title: 'land register extracts', type: ''},
            {name: 'result_appraisal', title: "appraisal fee", type: ''},
            {name: 'tip_purpose', title: 'Tip(Purpose)', type: 'tip'},
            {name: 'tip_type_property', title: 'Tip(Type of property)', type: 'tip'},
            {name: 'tip_purchasing', title: 'Tip(Purchasing price/Property value)', type: 'tip'},
            {name: 'tip_loan_amount', title: 'Tip(Loan amount required)', type: 'tip'},
            {name: 'tip_interest_variant', title: 'Tip(Interest rate variant)', type: 'tip'},
            {name: 'tip_loan_term', title: 'Tip(Loan term)', type: 'tip'},
            {name: 'tip_employment_type', title: 'Tip(Employment type)', type: 'tip'},
            {name: 'tip_preferred_date', title: 'Tip(Preferred payout data)', type: 'tip'},
            {name: 'tip_results', title: 'Tip(Results)', type: 'tip'},
            {name: 'tip_payment_rate', title: 'Tip(Payment rate)', type: 'tip'},
            {name: 'tip_borrowing_rate', title: 'Tip(Borrowing rate)', type: 'tip'},
            {name: 'tip_effective_rate', title: 'Tip(Effective interest rate)', type: 'tip'},
            {name: 'tip_total_payment', title: 'Tip(Total payment)', type: 'tip'},
            {name: 'tip_info', title: 'Tip(Information)', type: 'tip'}
        ]
    },
    {
        name: 'individual',
        title: 'Personal data',
        children: [
            {name: 'input_guide', title: 'Input below data to get indidivudal payment rate', type: ''},
            {name: 'person', title: 'Person', type: ''},
            {name: 'address', title: 'Address', type: ''},
            {name: 'street', title: 'Street', type: ''},
            {name: 'nr', title: 'Nr.', type: ''},
            {name: 'zip_code', title: 'Zip Code', type: ''},
            {name: 'city', title: 'City', type: ''},
            {name: 'country', title: 'Country', type: ''},
            {name: 'own_funds', title: 'Own funds', type: ''},
            {name: 'sum_own_funds', title: 'Sum own funds', type: ''},
            {name: 'guarantor', title: 'Guarantor', type: ''},
            {name: 'sum_guarantor', title: 'Sum guarantor', type: ''},
            {name: 'check_potential', title: 'Check portential', type: ''},
            {name: 'yes', title: 'Yes', type: ''},
            {name: 'no', title: 'No', type: ''},
            {name: 'result', title: 'Result', type: ''},
            {name: 'general_criteria', title: 'General criteria', type: ''},
            {name: 'attractiveness', title: 'Attractiveness', type: ''},
            {name: 'financing_attractive_sufficient', title: 'Financing is sufficiently attractive', type: ''},
            {name: 'financiing_attractive', title: 'Financing is attractive', type: ''},
            {name: 'financing_attractive_very', title: 'Financing is very attractive', type: ''},
            {name: 'financing_not_enough', title: 'Financing is not attractive enough', type: ''},
            {name: 'criteria_ok_but', title: 'Criteria are OK but financing volume maybe too small', type: ''},
            {name: 'financing_criteria_good', title: "Financing criteria and financing volume are good", type: ''},
            {name: 'infotext_like', title: 'Infotext like: Login to save data'},
            {name: 'tip_person_2', title: 'Tip(Person 2)', type: 'tip'},
            {name: 'tip_martial_status', title: 'Tip(Martial Status)', type: 'tip'},
            {name: 'tip_age', title: 'Tip(Age)', type: 'tip'},            
            {name: 'tip_net_income', title: 'Tip(Net income)', type: 'tip'},
            {name: 'tip_highest_degree', title: 'Tip(Highest degree)', type: 'tip'},
            {name: 'tip_field_work', title: 'Tip(Field of work)', type: 'tip'},
            {name: 'tip_job_position', title: 'Tip(Job position)', type: 'tip'},
            {name: 'tip_kids', title: 'Tip(Number of kids)', type: 'tip'},
            {name: 'tip_address', title: 'Tip(Address)', type: 'tip'},
            {name: 'tip_own_funds', title: 'Tip(Own funds)', type: 'tip'},
            {name: 'tip_sum_own_funds', title: 'Tip(Sum own funds)', type: 'tip'},
            {name: 'tip_guarantor', title: 'Tip(Guarantor)', type: 'tip'},
            {name: 'tip_sum_guarantor', title: 'Tip(Sum guarantor)', type: 'tip'},
            {name: 'tip_results', title: 'Tip(Results)', type: 'tip'},
            {name: 'tip_general_criteria', title: 'Tip(General criteria)', type: 'tip'},
            {name: 'tip_attractiveness', title: 'Tip(Attractiveness)', type: 'tip'},
        ]
    },
    {
        name: 'special',
        title: 'Project data',
        children: [
            {name: 'input_guide', title: 'Input below data to check potential', type: ''},
            {name: 'natural_disasters', title: 'Natural disasters', type: ''},
            {name: 'flood_vulnerability', title: 'Flood vulnerability', type: ''},
            {name: 'storm_hazard', title: 'Storm hazard', type: ''},
            {name: 'avalanche_mudstream', title: 'Avalanche/mudstream risk', type: ''},
            {name: 'forest_fire', title: 'Forest fire risk', type: ''},
            {name: 'years', title: 'Years', type: ''},
            {name: 'areas', title: 'Areas', type: ''},
            {name: 'building', title: 'Building ground', type: ''},
            {name: 'green', title: 'Green area', type: ''},
            {name: 'wood', title: 'Wood', type: ''},
            {name: 'others', title: 'Others', type: ''},
            {name: 'additions', title: 'Additions', type: ''},
            {name: 'alarm', title: 'Alarm system', type: ''},
            {name: 'underfloor_heating', title: 'Underfloor heating', type: ''},
            {name: 'home_ventilation', title: 'Home ventilation system', type: ''},
            {name: 'heat_pump', title: 'Heat pump', type: ''},
            {name: 'solar_photo', title: 'Solar power system/phto voltatic system', type: ''},
            {name: 'swimming', title: 'Swimming pool/pond', type: ''},
            {name: 'smart_home', title: 'Smart Home', type: ''},
            {name: 'window_shadowing', title: 'Window shadowing', type: ''},
            {name: 'garge', title: 'Garage/Carport', type: ''},
            {name: 'terrace', title: 'Terrace/balcony'},
            {name: 'tip_address', title: 'Tip(Address)', type: 'tip'},
            {name: 'tip_natural_disasters', title: 'Tip(Natural disasters)', type: 'tip'},
            {name: 'tip_areas', title: 'Tip(Areas)', type: 'tip'},
            {name: 'tip_Additions', title: 'Tip(Additions)', type: 'tip'}
        ]
    },
    {
        name: 'houldhold',
        title: 'Household bill',
        children: [
            {name: 'income_earnings', title: 'Income/Earnings', type: ''},
            {name: 'net', title: 'Net income/net earnings', type: ''}, 
            {name: 'other', title: 'Other income', type: ''},
            {name: 'family', title: 'Family allowances', type: ''}, 
            {name: 'expenses', title: 'Expenses', type: ''}, 
            {name: 'living_costs', title: 'Living costs', type: ''}, 
            {name: 'service_changes', title: 'Service changes', type: ''},
            {name: 'energy', title: 'Energy(Electricity, power, gas etc...)', type: ''},
            {name: 'tv_radio', title: 'TV, radio', type: ''},
            {name: 'streaming', title: 'Streaming, subscriptions,...', type: ''},
            {name: 'phone', title: 'Phone', type: ''},
            {name: 'internet', title: 'Internet', type: ''},
            {name: 'mobility', title: 'Mobility', type: ''},
            {name: 'motor_rate', title: 'Motor vehicle leasing rate', type: ''}, 
            {name: 'motor_taxes', title: 'Motor vehicel inisurance inc. taxes', type: ''},
            {name: 'fuel', title: 'Fuel', type: ''},
            {name: 'maintenance', title: 'Maintenance/repair', type: ''},
            {name: 'public_transportation', title: 'Public tansportation', type: ''},
            {name: 'insurances', title: 'Insurances', type: ''},
            {name: 'life', title: 'Life insurance', type: ''},
            {name: 'household_insurance', title: 'Household insurance', type: ''},
            {name: 'accident', title: 'Accident insurance', type: ''},
            {name: 'health', title: 'Health insurance', type: ''}, 
            {name: 'own-occupation', title: 'Own-occupation disability insurance', type: ''},
            {name: 'other_expenses', title: 'Other expenses', type: ''},
            {name: 'existing', title: 'Existing obligation/loan', type: ''},
            {name: 'recreational', title: 'Recreational expenses', type: ''},
            {name: 'vacation', title: 'Vacation/Holiday', type: ''},
            {name: 'other_household', title: 'Other household expenses', type: ''}, 
            {name: 'other_expenses', title: 'Other expenses', type: ''},
            {name: 'others_1', title: 'Others', type: ''},
            {name: 'existing_assets', title: 'Existing assets', type: ''},
            {name: 'saving', title: 'Savings bank account', type: ''},
            {name: 'building', title: 'Building loan contract', type: ''},
            {name: 'variable', title: 'Variable universal life insurance', type: ''},
            {name: 'investment', title: 'Investmentfunds', type: ''},
            {name: 'real_estate', title: 'Real estate'},
            {name: 'tip_income', title: 'Tip(Income)', type: 'tip'},
            {name: 'tip_net', title: 'Tip(Net income/net earnings*)', type: 'tip'},
            {name: 'tip_other', title: 'Tip(Other income)', type: 'tip'},
            {name: 'tip_expenses', title: 'Tip(Expenses)', type: 'tip'},
            {name: 'tip_living_costs', title: 'Tip(Living costs)', type: 'tip'},
            {name: 'tip_mobility', title: 'Tip(Mobility)', type: 'tip'},
            {name: 'tip_insurances', title: 'Tip(Insurances)', type: 'tip'},
            {name: 'tip_other_expenses', title: 'Tip(Other expenses)', type: 'tip'},
            {name: 'tip_existing_assets', title: 'Tip(Existing assets)', type: 'tip'},
            {name: 'tip_summary', title: 'Tip(Summary)', type: 'tip'},
            
        ]
    },
    {
        name: 'livingspace',
        title: 'Living space information',
        children: [
            {name: 'floor', title: 'Floor', type: ''},
            {name: 'living_room', title: 'Living room#', type: ''},
            {name: 'dinning_room', title: 'Dinning room#', type: ''},
            {name: 'kitchen', title: 'Kitchen#', type: ''},
            {name: 'bathroom', title: 'Bathroom#', type: ''},
            {name: 'lavatory', title: 'Lavatory#', type: ''},
            {name: 'outer_room', title: 'Outer room#', type: ''},
            {name: 'wardrobe', title: 'Wardrobe#', type: ''},
            {name: 'larder', title: 'Larder#', type: ''},
            {name: 'bedroom', title: 'Bedroom#', type: ''},
            {name: 'children', title: "Children's room#", type: ''},
            {name: 'hailways', title: 'Hailways#', type: ''},
            {name: 'closet', title: 'Closet#', type: ''},
            {name: 'storeroom', title: 'Storeroom#', type: ''},
            {name: 'technical_room', title: 'Technical room', type: ''},
            {name: 'other_rooms', title: 'Other rooms', type: ''},
            {name: 'additional_room', title: 'Additional room#', type: ''},
            {name: 'sum', title: 'Sum', type: ''},
            {name: 'sum_floors', title: 'Sum Floors', type: ''},
            {name: 'sum_living', title: 'Sum Living', type: ''},
            {name: 'tip_floor_1', title: 'Tip(Existing assets)', type: 'tip'},
            {name: 'tip_floor_other', title: 'Tip(Existing assets)', type: 'tip'}
        ]
    },
    {
        name: 'project_cost',
        title: 'Project cost overview',
        children: [
            {name: 'housebuilding', title: 'Housebuilding', type: ''},
            {name: 'offered_purchasing', title: 'Offered purchasing price', type: ''},
            {name: 'painting_hours', title: 'Painting incl. working hours', type: ''},
            {name: 'floor_assemb', title: 'Floor incl. assembling#', type: ''},
            {name: 'bathroom_assemb', title: 'Bathroom incl. assembling#', type: ''},
            {name: 'kitchen', title: 'Kitchen', type: ''},
            {name: 'other_interior', title: 'Other interior costs#(1)', type: ''},
            {name: 'other_permanently', title: 'Other permanently installed costs', type: ''},
            {name: 'turnkey_ready', title: 'Turnkey ready#', type: ''}, 
            {name: 'basement', title: 'Basement', type: ''},
            {name: 'cellar_additionals', title: 'Cellar/foundation incl. additionals', type: ''},
            {name: 'ground', title: 'Ground(Building area, etc.)'},
            {name: 'exterior', title: 'Exterior', type: ''},
            {name: 'garage_carport', title: 'Garage/Carport', type: ''},
            {name: 'terrace_balcony', title: 'Terrace/balcony', type: ''},
            {name: 'roofing', title: 'Roofing(terrace etc.)', type: ''},
            {name: 'swimming_pool', title: 'Swimming pool/pond', type: ''},
            {name: 'fence', title: 'Fence', type: ''},
            {name: 'landscaping', title: 'Landscaping', type: ''},
            {name: 'roads_etc', title: 'Roads, paths, paving stones etc', type: ''},
            {name: 'other_exterior_costs', title: 'Other exterior costs#', type: ''},
            {name: 'independent', title: 'Independent', type: ''},
            {name: 'road_charges', title: 'Road/connection charges(1)', type: ''},
            {name: 'land_registry', title: 'Land registry', type: ''},
            {name: 'land_bank', title: 'Land registry Bank', type: ''},
            {name: 'stamp_duty', title: 'Stamp duty', type: ''},
            {name: 'handling_fee', title: 'Handling fee', type: ''},
            {name: 'external_etc', title: 'External notary, lawyer etc.', type: ''},
            {name: 'survayor', title: 'Survayor', type: ''},
            {name: 'other_independent_costs', title: 'Other independent costs', type: ''},
            {name: 'project_sum', title: 'Project costs', type: ''},
            {name: 'fundable_sum', title: 'Fundable costs'},
            {name: 'tip_housebuilding', title: 'Tip(Housebuilding)', type: 'tip'},
            {name: 'tip_offered_purchasing', title: 'Tip(Offered purchasing price)', type: 'tip'},
            {name: 'tip_other_permanently', title: 'Tip(Other permanently installed costs)', type: 'tip'},
            {name: 'tip_other_interior', title: 'Tip(Other interior costs)', type: 'tip'},
            {name: 'tip_turnkey_ready', title: 'Tip(Turnkey ready)', type: 'tip'},
            {name: 'tip_basement', title: 'Tip(Basement costs)', type: 'tip'},            
            {name: 'tip_cellar_additionals', title: 'Tip(Cellar/foundation incl. additionals)', type: 'tip'},
            {name: 'tip_ground', title: 'Tip(Building ground)', type: 'tip'},
            {name: 'tip_exterior', title: 'Tip(Exterior costs)', type: 'tip'},            
            {name: 'tip_independent', title: 'Tip(Independent costs)', type: 'tip'},        
            {name: 'tip_road_charges', title: 'Tip(Road/connection charges)', type: 'tip'},
            {name: 'tip_land_registry', title: 'Tip(Land registry)', type: 'tip'}, 
            {name: 'tip_land_bank', title: 'Tip(Land registry Bank)', type: 'tip'},     
            {name: 'tip_stamp_duty', title: 'Tip(Stamp duty)', type: 'tip'},           
            {name: 'tip_handling_fee', title: 'Tip(Handling fee)', type: 'tip'},            
            {name: 'tip_external_etc', title: 'Tip(External notary, lawyer etc.)', type: 'tip'},
            {name: 'tip_survayor', title: 'Tip(Survayor)', type: 'tip'},
            {name: 'tip_other_independent_costs', title: 'Tip(Other independent costs)', type: 'tip'},
            {name: 'tip_project_sum', title: 'Tip(Project costs)', type: 'tip'},            
            {name: 'tip_fundable_sum', title: 'Tip(Fundable costs)', type: 'tip'},
            {name: 'tip_output_housebuilding', title: 'Tip(Housebuilding costs)', type: 'tip'},
            {name: 'tip_output_basement', title: 'Tip(Basement costs)', type: 'tip'},
            {name: 'tip_output_exterior', title: 'Tip(Exterior costs)', type: 'tip'},
            {name: 'tip_output_independent', title: 'Tip(Independent costs)', type: 'tip'}
        ]
    },
    {
        name: 'documents',
        title: 'Documents',
        children: [
            {name: 'no_file', title: 'No file uploaded', type: ''},
            {name: 'identification', title: 'Identification', type: ''},
            {name: 'statement_bank', title: 'Statement of bank account', type: ''},
            {name: 'pay_slip', title: 'Pay slip/proof of income*', type: ''},
            {name: 'proof_assets', title: 'Proof of assets(*)', type: ''},
            {name: 'house_offer', title: 'House offer*', type: ''},
            {name: 'basement', title: 'Basement/ Foundation/ Cellar offer*', type: ''},
            {name: 'id_guarantor', title: 'ID guarantor(*)', type: ''},
            {name: 'proof_guarantor', title: 'Proof of assets guarantor(*)', type: ''},
            {name: 'deed_suretyship', title: 'Deed of suretyship'},
            {name: 'tip_identification', title: 'Tip(Identification)', type: 'tip'},
            {name: 'tip_statement_bank', title: 'Tip(Statement of bank account)', type: 'tip'},
            {name: 'tip_pay_slip', title: 'Tip(Pay slip/proof of income*)', type: 'tip'},
            {name: 'tip_proof_assets', title: 'Tip(Proof of assets(*))', type: 'tip'},
            {name: 'tip_house_offer', title: 'Tip(House offer*)', type: 'tip'},
            {name: 'tip_basement', title: 'Tip(Basement/ Foundation/ Cellar offer*)', type: 'tip'},
            {name: 'tip_id_guarantor', title: 'Tip(ID guarantor(*)', type: 'tip'},
            {name: 'tip_proof_guarantor', title: 'Proof of assets guarantor(*)', type: 'tip'},
            {name: 'tip_deed_suretyship', title: 'Tip(Deed of suretyship', type: 'tip'},


        ]
    },
    {
        name: 'dashboard',
        title: 'Dashboard',
        children: [
            {name: 'new_loan_application', title: 'New loan application', type: ''},
            {name: 'messages', title: 'Messages', type: ''},
            {name: 'my_loans', title: 'My Loans', type: ''},
            {name: 'messages', title: 'Messages', type: ''},
            {name: 'introduction', title: 'Introduction', type: ''},
            {name: 'welcome', title: 'Welcome to our platform!', type: ''},
            {name: 'advisor', title: 'Advisor', type: ''},
            {name: 'loan', title: 'Loan', type: ''},
            {name: 'application_uploaded', title: 'Application uploaded successfully(ID)', type: ''},
            {name: 'create_document', title: 'Create Document'},
            {name: 'settings', title: 'Settings', type: ''},
            {name: 'loan_name', title: 'Loan name', type: ''},
            {name: 'id', title: 'ID', type: ''},
            {name: 'start', title: 'Start', type: ''},            
            {name: 'end', title: 'End', type: ''},            
            {name: 'loan_amount', title: 'Loan Amount', type: ''},            
            {name: 'state', title: 'State', type: ''},            
            {name: 'active', title: 'Active', type: ''},            
            {name: 'application', title: 'Application', type: ''},            
            {name: 'default', title: 'Default', type: ''},            
            {name: 'repaid', title: 'Repaid', type: ''},            
            {name: 'arrears', title: 'Arrears', type: ''},            
            {name: 'construction', title: 'Construction', type: ''},
            {name: 'open', title: 'Open', type: ''},
        ]
    },
    {
        name: 'loan_details',
        title: 'Loan details',
        children: [
            {name: 'current_repyament_rate', title: 'Currernt repayment rate', type: ''},
            {name: 'current_lending_rate', title: 'Current lending rate', type: ''},
            {name: 'type_of_interest_rate', title: 'Type of interest rate', type: ''},
            {name: 'variable', title: 'Variable', type: ''},
            {name: 'loan_maturity', title: 'Loan maturity', type: ''},
            {name: 'years', title: 'years', type: ''},
            {name: 'remaining_term', title: 'Remaining Term', type: ''},
            {name: 'loan_adjustment', title: 'Loan adjustment', type: ''},
            {name: 'loan_data', title: 'Loan Data', type: ''},
            {name: 'repayment_rate', title: 'Repayment rate', type: ''},
            {name: 'interest', title: 'Interest', type: ''},       
            {name: 'outstanding', title: 'Outstanding', type: ''},            
            {name: 'current_situation', title: 'Current situation', type: ''},            
            {name: 'current_remaining_debt', title: 'Current remaining debt', type: ''},            
            {name: 'total_additional_interest_payments', title: 'Total additional interest payments:', type: ''},
            {name: 'open_repayment_plan', title: 'Open repayment Plan', type: ''},   
            {name: 'calculate', title: 'Calculate', type: ''},   
            {name: 'add_new_stress_scenario', title: 'Add new stress scenario', type: ''},            
            {name: 'no_stress_scenario_added', title: 'No stress scenario added!', type: ''},            
            {name: 'stressscenario', title: 'Stress Sceario', type: ''},
            {name: 'stressscenario_duplicated', title: 'Stress Scenarios are duplicated.', type: ''},
            {name: 'stressscenario_duplicated_msg', title: "You can't set two stress scenarios on the same time! Please change start and end.", type: 'tip'},
        ]
    }
];